---
- name: Update lava Node Binary
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.10  # Explicit Python path
    lavad_version_url: "3.1.0"
    lavad_version_path: "3.1.0"
    lava_directory: "/root/.lava"
    lava_binary_url: "https://github.com/lavanet/lava/releases/download/v{{ lavad_version_url }}/lavad-v{{ lavad_version_url }}-linux-amd64"
    binary_path: "/usr/local/bin/lavad"

  tasks:
    - name: Stop lava node service
      systemd:
        name: lavad
        state: stopped

    - name: Download new lava binary
      get_url:
        url: "{{ lava_binary_url }}"
        dest: "/tmp/lavad-{{ lavad_version_url }}-linux-amd64"
        mode: '0755'

    - name: Replace old binary with new binary
      copy:
        src: "/tmp/lavad-{{ lavad_version_url }}-linux-amd64"
        dest: "{{ binary_path }}"
        remote_src: yes
        force: yes

    - name: Set executable permissions on the new binary
      file:
        path: "{{ binary_path }}"
        mode: '0755'

    - name: Prepare directory for new binary in Cosmovisor
      file:
        path: "{{ lava_directory }}/cosmovisor/upgrades/v{{ lavad_version_path }}/bin"
        state: directory

    - name: Copy new binary to Cosmovisor upgrade directory
      copy:
        src: "/tmp/lavad-{{ lavad_version_url }}-linux-amd64"
        dest: "{{ lava_directory }}/cosmovisor/upgrades/v{{ lavad_version_path }}/bin/lavad"
        mode: '0755'
        remote_src: yes

    - name: Copy new binary to genesis directory
      copy:
        src: "/tmp/lavad-{{ lavad_version_url }}-linux-amd64"
        dest: "/root/.lava/cosmovisor/genesis/bin/lavad"
        remote_src: yes
        force: yes

    - name: Remove temporary binary file
      file:
        path: "/tmp/lavad-{{ lavad_version_url }}-linux-amd64"
        state: absent

